// Code generated by MockGen. DO NOT EDIT.
// Source: server.go

// Package mock_worker is a generated GoMock package.
package mock_worker

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDatabaseVault is a mock of DatabaseVault interface.
type MockDatabaseVault struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseVaultMockRecorder
}

// MockDatabaseVaultMockRecorder is the mock recorder for MockDatabaseVault.
type MockDatabaseVaultMockRecorder struct {
	mock *MockDatabaseVault
}

// NewMockDatabaseVault creates a new mock instance.
func NewMockDatabaseVault(ctrl *gomock.Controller) *MockDatabaseVault {
	mock := &MockDatabaseVault{ctrl: ctrl}
	mock.recorder = &MockDatabaseVaultMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabaseVault) EXPECT() *MockDatabaseVaultMockRecorder {
	return m.recorder
}

// AddData mocks base method.
func (m *MockDatabaseVault) AddData(login, description string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddData", login, description, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddData indicates an expected call of AddData.
func (mr *MockDatabaseVaultMockRecorder) AddData(login, description, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddData", reflect.TypeOf((*MockDatabaseVault)(nil).AddData), login, description, data)
}

// CreateNewUser mocks base method.
func (m *MockDatabaseVault) CreateNewUser(login string, password, signKeyComplicated, key []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNewUser", login, password, signKeyComplicated, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNewUser indicates an expected call of CreateNewUser.
func (mr *MockDatabaseVaultMockRecorder) CreateNewUser(login, password, signKeyComplicated, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNewUser", reflect.TypeOf((*MockDatabaseVault)(nil).CreateNewUser), login, password, signKeyComplicated, key)
}

// GetAllData mocks base method.
func (m *MockDatabaseVault) GetAllData(login string) ([][]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllData", login)
	ret0, _ := ret[0].([][]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllData indicates an expected call of GetAllData.
func (mr *MockDatabaseVaultMockRecorder) GetAllData(login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllData", reflect.TypeOf((*MockDatabaseVault)(nil).GetAllData), login)
}

// GetData mocks base method.
func (m *MockDatabaseVault) GetData(login, description string) ([][]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetData", login, description)
	ret0, _ := ret[0].([][]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetData indicates an expected call of GetData.
func (mr *MockDatabaseVaultMockRecorder) GetData(login, description interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetData", reflect.TypeOf((*MockDatabaseVault)(nil).GetData), login, description)
}

// GetUserKey mocks base method.
func (m *MockDatabaseVault) GetUserKey(login string) ([]byte, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserKey", login)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUserKey indicates an expected call of GetUserKey.
func (mr *MockDatabaseVaultMockRecorder) GetUserKey(login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserKey", reflect.TypeOf((*MockDatabaseVault)(nil).GetUserKey), login)
}

// GetUserPassword mocks base method.
func (m *MockDatabaseVault) GetUserPassword(login string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPassword", login)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPassword indicates an expected call of GetUserPassword.
func (mr *MockDatabaseVaultMockRecorder) GetUserPassword(login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPassword", reflect.TypeOf((*MockDatabaseVault)(nil).GetUserPassword), login)
}
