// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package mock_worker is a generated GoMock package.
package mock_worker

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTunnelToServer is a mock of TunnelToServer interface.
type MockTunnelToServer struct {
	ctrl     *gomock.Controller
	recorder *MockTunnelToServerMockRecorder
}

// MockTunnelToServerMockRecorder is the mock recorder for MockTunnelToServer.
type MockTunnelToServerMockRecorder struct {
	mock *MockTunnelToServer
}

// NewMockTunnelToServer creates a new mock instance.
func NewMockTunnelToServer(ctrl *gomock.Controller) *MockTunnelToServer {
	mock := &MockTunnelToServer{ctrl: ctrl}
	mock.recorder = &MockTunnelToServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTunnelToServer) EXPECT() *MockTunnelToServerMockRecorder {
	return m.recorder
}

// GetAllData mocks base method.
func (m *MockTunnelToServer) GetAllData(login string, dat []byte) ([][]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllData", login, dat)
	ret0, _ := ret[0].([][]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllData indicates an expected call of GetAllData.
func (mr *MockTunnelToServerMockRecorder) GetAllData(login, dat interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllData", reflect.TypeOf((*MockTunnelToServer)(nil).GetAllData), login, dat)
}

// GetData mocks base method.
func (m *MockTunnelToServer) GetData(login string, dat []byte) ([][]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetData", login, dat)
	ret0, _ := ret[0].([][]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetData indicates an expected call of GetData.
func (mr *MockTunnelToServerMockRecorder) GetData(login, dat interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetData", reflect.TypeOf((*MockTunnelToServer)(nil).GetData), login, dat)
}

// Login mocks base method.
func (m *MockTunnelToServer) Login(login string, password []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", login, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// Login indicates an expected call of Login.
func (mr *MockTunnelToServerMockRecorder) Login(login, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockTunnelToServer)(nil).Login), login, password)
}

// Registration mocks base method.
func (m *MockTunnelToServer) Registration(login, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Registration", login, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// Registration indicates an expected call of Registration.
func (mr *MockTunnelToServerMockRecorder) Registration(login, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Registration", reflect.TypeOf((*MockTunnelToServer)(nil).Registration), login, password)
}

// SaveData mocks base method.
func (m *MockTunnelToServer) SaveData(login string, dat []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveData", login, dat)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveData indicates an expected call of SaveData.
func (mr *MockTunnelToServerMockRecorder) SaveData(login, dat interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveData", reflect.TypeOf((*MockTunnelToServer)(nil).SaveData), login, dat)
}
