// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: objects.proto

package protobufproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cred struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Login       *string                `protobuf:"bytes,1,opt,name=login"`
	xxx_hidden_Password    []byte                 `protobuf:"bytes,2,opt,name=password"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Cred) Reset() {
	*x = Cred{}
	mi := &file_objects_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cred) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cred) ProtoMessage() {}

func (x *Cred) ProtoReflect() protoreflect.Message {
	mi := &file_objects_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Cred) GetLogin() string {
	if x != nil {
		if x.xxx_hidden_Login != nil {
			return *x.xxx_hidden_Login
		}
		return ""
	}
	return ""
}

func (x *Cred) GetPassword() []byte {
	if x != nil {
		return x.xxx_hidden_Password
	}
	return nil
}

func (x *Cred) SetLogin(v string) {
	x.xxx_hidden_Login = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *Cred) SetPassword(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Password = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *Cred) HasLogin() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Cred) HasPassword() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Cred) ClearLogin() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Login = nil
}

func (x *Cred) ClearPassword() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Password = nil
}

type Cred_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Login    *string
	Password []byte
}

func (b0 Cred_builder) Build() *Cred {
	m0 := &Cred{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Login != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Login = b.Login
	}
	if b.Password != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Password = b.Password
	}
	return m0
}

type Note struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Login       *string                `protobuf:"bytes,1,opt,name=login"`
	xxx_hidden_Data        []byte                 `protobuf:"bytes,2,opt,name=data"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Note) Reset() {
	*x = Note{}
	mi := &file_objects_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Note) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Note) ProtoMessage() {}

func (x *Note) ProtoReflect() protoreflect.Message {
	mi := &file_objects_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Note) GetLogin() string {
	if x != nil {
		if x.xxx_hidden_Login != nil {
			return *x.xxx_hidden_Login
		}
		return ""
	}
	return ""
}

func (x *Note) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *Note) SetLogin(v string) {
	x.xxx_hidden_Login = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *Note) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *Note) HasLogin() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Note) HasData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Note) ClearLogin() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Login = nil
}

func (x *Note) ClearData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Data = nil
}

type Note_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Login *string
	Data  []byte
}

func (b0 Note_builder) Build() *Note {
	m0 := &Note{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Login != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Login = b.Login
	}
	if b.Data != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Data = b.Data
	}
	return m0
}

type SavedNotes struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Notes *[]*Note               `protobuf:"bytes,2,rep,name=Notes"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SavedNotes) Reset() {
	*x = SavedNotes{}
	mi := &file_objects_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SavedNotes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavedNotes) ProtoMessage() {}

func (x *SavedNotes) ProtoReflect() protoreflect.Message {
	mi := &file_objects_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SavedNotes) GetNotes() []*Note {
	if x != nil {
		if x.xxx_hidden_Notes != nil {
			return *x.xxx_hidden_Notes
		}
	}
	return nil
}

func (x *SavedNotes) SetNotes(v []*Note) {
	x.xxx_hidden_Notes = &v
}

type SavedNotes_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Notes []*Note
}

func (b0 SavedNotes_builder) Build() *SavedNotes {
	m0 := &SavedNotes{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Notes = &b.Notes
	return m0
}

type Err struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Err) Reset() {
	*x = Err{}
	mi := &file_objects_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Err) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Err) ProtoMessage() {}

func (x *Err) ProtoReflect() protoreflect.Message {
	mi := &file_objects_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type Err_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 Err_builder) Build() *Err {
	m0 := &Err{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_objects_proto protoreflect.FileDescriptor

const file_objects_proto_rawDesc = "" +
	"\n" +
	"\robjects.proto\x12\rprotobufproto\x1a!google/protobuf/go_features.proto\"8\n" +
	"\x04Cred\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\fR\bpassword\"0\n" +
	"\x04Note\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"7\n" +
	"\n" +
	"SavedNotes\x12)\n" +
	"\x05Notes\x18\x02 \x03(\v2\x13.protobufproto.NoteR\x05Notes\"\x05\n" +
	"\x03Err2\xa5\x02\n" +
	"\n" +
	"GRPService\x127\n" +
	"\fRegistration\x12\x13.protobufproto.Cred\x1a\x12.protobufproto.Err\x120\n" +
	"\x05Login\x12\x13.protobufproto.Cred\x1a\x12.protobufproto.Err\x123\n" +
	"\bSaveData\x12\x13.protobufproto.Note\x1a\x12.protobufproto.Err\x129\n" +
	"\aGetData\x12\x13.protobufproto.Note\x1a\x19.protobufproto.SavedNotes\x12<\n" +
	"\n" +
	"GetAllData\x12\x13.protobufproto.Note\x1a\x19.protobufproto.SavedNotesB\x1dZ\x13proto/protobufproto\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_objects_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_objects_proto_goTypes = []any{
	(*Cred)(nil),       // 0: protobufproto.Cred
	(*Note)(nil),       // 1: protobufproto.Note
	(*SavedNotes)(nil), // 2: protobufproto.SavedNotes
	(*Err)(nil),        // 3: protobufproto.Err
}
var file_objects_proto_depIdxs = []int32{
	1, // 0: protobufproto.SavedNotes.Notes:type_name -> protobufproto.Note
	0, // 1: protobufproto.GRPService.Registration:input_type -> protobufproto.Cred
	0, // 2: protobufproto.GRPService.Login:input_type -> protobufproto.Cred
	1, // 3: protobufproto.GRPService.SaveData:input_type -> protobufproto.Note
	1, // 4: protobufproto.GRPService.GetData:input_type -> protobufproto.Note
	1, // 5: protobufproto.GRPService.GetAllData:input_type -> protobufproto.Note
	3, // 6: protobufproto.GRPService.Registration:output_type -> protobufproto.Err
	3, // 7: protobufproto.GRPService.Login:output_type -> protobufproto.Err
	3, // 8: protobufproto.GRPService.SaveData:output_type -> protobufproto.Err
	2, // 9: protobufproto.GRPService.GetData:output_type -> protobufproto.SavedNotes
	2, // 10: protobufproto.GRPService.GetAllData:output_type -> protobufproto.SavedNotes
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_objects_proto_init() }
func file_objects_proto_init() {
	if File_objects_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_objects_proto_rawDesc), len(file_objects_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_objects_proto_goTypes,
		DependencyIndexes: file_objects_proto_depIdxs,
		MessageInfos:      file_objects_proto_msgTypes,
	}.Build()
	File_objects_proto = out.File
	file_objects_proto_goTypes = nil
	file_objects_proto_depIdxs = nil
}
