// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: objects.proto

package protobufproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GRPService_Registration_FullMethodName = "/protobufproto.GRPService/Registration"
	GRPService_Login_FullMethodName        = "/protobufproto.GRPService/Login"
	GRPService_SaveData_FullMethodName     = "/protobufproto.GRPService/SaveData"
	GRPService_GetData_FullMethodName      = "/protobufproto.GRPService/GetData"
	GRPService_GetAllData_FullMethodName   = "/protobufproto.GRPService/GetAllData"
)

// GRPServiceClient is the client API for GRPService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GRPServiceClient interface {
	Registration(ctx context.Context, in *Cred, opts ...grpc.CallOption) (*Err, error)
	Login(ctx context.Context, in *Cred, opts ...grpc.CallOption) (*Err, error)
	SaveData(ctx context.Context, in *Note, opts ...grpc.CallOption) (*Err, error)
	GetData(ctx context.Context, in *Note, opts ...grpc.CallOption) (*SavedNotes, error)
	GetAllData(ctx context.Context, in *Note, opts ...grpc.CallOption) (*SavedNotes, error)
}

type gRPServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGRPServiceClient(cc grpc.ClientConnInterface) GRPServiceClient {
	return &gRPServiceClient{cc}
}

func (c *gRPServiceClient) Registration(ctx context.Context, in *Cred, opts ...grpc.CallOption) (*Err, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Err)
	err := c.cc.Invoke(ctx, GRPService_Registration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPServiceClient) Login(ctx context.Context, in *Cred, opts ...grpc.CallOption) (*Err, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Err)
	err := c.cc.Invoke(ctx, GRPService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPServiceClient) SaveData(ctx context.Context, in *Note, opts ...grpc.CallOption) (*Err, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Err)
	err := c.cc.Invoke(ctx, GRPService_SaveData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPServiceClient) GetData(ctx context.Context, in *Note, opts ...grpc.CallOption) (*SavedNotes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SavedNotes)
	err := c.cc.Invoke(ctx, GRPService_GetData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPServiceClient) GetAllData(ctx context.Context, in *Note, opts ...grpc.CallOption) (*SavedNotes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SavedNotes)
	err := c.cc.Invoke(ctx, GRPService_GetAllData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GRPServiceServer is the server API for GRPService service.
// All implementations must embed UnimplementedGRPServiceServer
// for forward compatibility.
type GRPServiceServer interface {
	Registration(context.Context, *Cred) (*Err, error)
	Login(context.Context, *Cred) (*Err, error)
	SaveData(context.Context, *Note) (*Err, error)
	GetData(context.Context, *Note) (*SavedNotes, error)
	GetAllData(context.Context, *Note) (*SavedNotes, error)
	mustEmbedUnimplementedGRPServiceServer()
}

// UnimplementedGRPServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGRPServiceServer struct{}

func (UnimplementedGRPServiceServer) Registration(context.Context, *Cred) (*Err, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Registration not implemented")
}
func (UnimplementedGRPServiceServer) Login(context.Context, *Cred) (*Err, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedGRPServiceServer) SaveData(context.Context, *Note) (*Err, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveData not implemented")
}
func (UnimplementedGRPServiceServer) GetData(context.Context, *Note) (*SavedNotes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetData not implemented")
}
func (UnimplementedGRPServiceServer) GetAllData(context.Context, *Note) (*SavedNotes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllData not implemented")
}
func (UnimplementedGRPServiceServer) mustEmbedUnimplementedGRPServiceServer() {}
func (UnimplementedGRPServiceServer) testEmbeddedByValue()                    {}

// UnsafeGRPServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GRPServiceServer will
// result in compilation errors.
type UnsafeGRPServiceServer interface {
	mustEmbedUnimplementedGRPServiceServer()
}

func RegisterGRPServiceServer(s grpc.ServiceRegistrar, srv GRPServiceServer) {
	// If the following call pancis, it indicates UnimplementedGRPServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GRPService_ServiceDesc, srv)
}

func _GRPService_Registration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Cred)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPServiceServer).Registration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GRPService_Registration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPServiceServer).Registration(ctx, req.(*Cred))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Cred)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GRPService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPServiceServer).Login(ctx, req.(*Cred))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPService_SaveData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Note)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPServiceServer).SaveData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GRPService_SaveData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPServiceServer).SaveData(ctx, req.(*Note))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPService_GetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Note)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPServiceServer).GetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GRPService_GetData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPServiceServer).GetData(ctx, req.(*Note))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPService_GetAllData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Note)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPServiceServer).GetAllData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GRPService_GetAllData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPServiceServer).GetAllData(ctx, req.(*Note))
	}
	return interceptor(ctx, in, info, handler)
}

// GRPService_ServiceDesc is the grpc.ServiceDesc for GRPService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GRPService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobufproto.GRPService",
	HandlerType: (*GRPServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Registration",
			Handler:    _GRPService_Registration_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _GRPService_Login_Handler,
		},
		{
			MethodName: "SaveData",
			Handler:    _GRPService_SaveData_Handler,
		},
		{
			MethodName: "GetData",
			Handler:    _GRPService_GetData_Handler,
		},
		{
			MethodName: "GetAllData",
			Handler:    _GRPService_GetAllData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "objects.proto",
}
